
CREATE TABLE quiz (
    question_id SERIAL PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_1 TEXT NOT NULL,
    option_2 TEXT NOT NULL,
    option_3 TEXT,
    option_4 TEXT,
    correct_answer CHAR(1) NOT NULL
);

INSERT INTO quiz (question_text, option_1, option_2, option_3, option_4, correct_answer) VALUES
('What is 5 + 3?', '7', '8', '9', '10', 'B'),
('If you rearrange the letters "CIFAIPC" you would have the name of a:', 'City', 'Animal', 'Ocean', 'River', 'C'),
('What is the next number in the series: 2, 4, 6, 8, ...?', '10', '12', '14', '16', 'A'),
('Which is the largest planet in our solar system?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'C'),
('What is the square root of 64?', '6', '7', '8', '9', 'C'),
('If a train travels at 60 miles per hour, how long will it take to travel 180 miles?', '2 hours', '3 hours', '4 hours', '5 hours', 'B'),
('Which word does NOT belong with the others?', 'Apple', 'Banana', 'Carrot', 'Grape', 'C'),
('Which of the following is an even number?', '3', '5', '8', '11', 'C'),
('In which direction does the sun rise?', 'North', 'South', 'East', 'West', 'C'),
('What is the chemical symbol for water?', 'HO', 'H2O', 'O2H', 'OH2', 'B'),
('What is 12 * 12?', '124', '144', '154', '164', 'B'),
('Which planet is known as the "Red Planet"?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'B'),
('If 6x = 72, what is x?', '10', '11', '12', '13', 'C'),
('What is the capital of France?', 'Paris', 'London', 'Berlin', 'Madrid', 'A'),
('Which is the smallest prime number?', '0', '1', '2', '3', 'C'),
('If you write the numbers from 1 to 100, how many times do you write the digit 1?', '10', '11', '20', '21', 'D'),
('What is the value of π (pi) to two decimal places?', '3.12', '3.13', '3.14', '3.15', 'C'),
('What is the boiling point of water?', '90°C', '100°C', '110°C', '120°C', 'B'),
('What is 9^2?', '80', '81', '82', '83', 'B'),
('Which of the following is a leap year?', '1900', '2000', '2002', '2003', 'B'),
('Which is the longest river in the world?', 'Nile', 'Amazon', 'Yangtze', 'Mississippi', 'A'),
('How many continents are there?', '5', '6', '7', '8', 'C'),
('What is the currency of Japan?', 'Yen', 'Won', 'Dollar', 'Euro', 'A'),
('What is the largest ocean on Earth?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 'D'),
('If 3y = 36, what is y?', '10', '11', '12', '13', 'C'),
('What is the sum of angles in a triangle?', '180 degrees', '360 degrees', '90 degrees', '270 degrees', 'A'),
('Which country is known as the Land of the Rising Sun?', 'China', 'Japan', 'Korea', 'India', 'B'),
('What is the square of 15?', '215', '225', '235', '245', 'B'),
('Which is the largest desert in the world?', 'Sahara', 'Gobi', 'Arabian', 'Kalahari', 'A'),
('What is the main ingredient in bread?', 'Rice', 'Flour', 'Sugar', 'Salt', 'B'),
('Which of the following is a mammal?', 'Shark', 'Frog', 'Whale', 'Crocodile', 'C'),
('If a = 5, b = 6, what is a + b?', '10', '11', '12', '13', 'B'),
('What is the freezing point of water?', '0°C', '32°C', '100°C', '212°C', 'A'),
('How many sides does a hexagon have?', '5', '6', '7', '8', 'B'),
('Which is the largest continent?', 'Africa', 'Asia', 'Europe', 'Australia', 'B'),
('Who is the author of "Romeo and Juliet"?', 'Charles Dickens', 'Mark Twain', 'William Shakespeare', 'Jane Austen', 'C'),
('What is 1000 divided by 25?', '20', '30', '40', '50', 'C'),
('What is the capital of Italy?', 'Rome', 'Paris', 'Berlin', 'Madrid', 'A'),
('Which gas is most abundant in the Earth’s atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'B'),
('Which planet is closest to the sun?', 'Venus', 'Mars', 'Mercury', 'Earth', 'C'),
('How many colors are there in a rainbow?', '5', '6', '7', '8', 'C'),
('What is the square root of 81?', '7', '8', '9', '10', 'C'),
('Which of the following is a renewable resource?', 'Coal', 'Oil', 'Natural Gas', 'Solar Energy', 'D'),
('What is the capital of Germany?', 'Paris', 'Berlin', 'Madrid', 'Rome', 'B'),
('If 2a = 8, what is a?', '2', '3', '4', '5', 'C'),
('What is the largest mammal in the world?', 'Elephant', 'Blue Whale', 'Giraffe', 'Great White Shark', 'B'),
('Which is the smallest ocean in the world?', 'Atlantic', 'Indian', 'Arctic', 'Southern', 'C'),
('Who invented the telephone?', 'Alexander Graham Bell', 'Thomas Edison', 'Nikola Tesla', 'Albert Einstein', 'A'),
('What is 7 + 8?', '14', '15', '16', '17', 'B'),
('Which planet is known as the Earths twin?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'A'),
('What is the formula for calculating the area of a circle?', 'πr²', '2πr', 'πd', '2r', 'A'),
('Which element is represented by the symbol "O"?', 'Gold', 'Oxygen', 'Osmium', 'Iron', 'B'),
('How many degrees are in a right angle?', '45', '90', '180', '360', 'B'),
('Who was the first president of the United States?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams', 'A'),
('What is the capital of Canada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 'B'),
('Which number is both a square and a cube?', '8', '16', '27', '64', 'D'),
('What is the sum of the internal angles of a quadrilateral?', '180 degrees', '360 degrees', '270 degrees', '90 degrees', 'B'),
('Who wrote "To Kill a Mockingbird"?', 'Harper Lee', 'Mark Twain', 'F. Scott Fitzgerald', 'Ernest Hemingway', 'A'),
('What is the largest bone in the human body?', 'Femur', 'Tibia', 'Humerus', 'Skull', 'A'),
('Which gas do plants absorb from the atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'C'),
('What is the smallest unit of matter?', 'Atom', 'Molecule', 'Proton', 'Electron', 'A'),
('What is 10% of 200?', '15', '20', '25', '30', 'B'),
('Who discovered penicillin?', 'Marie Curie', 'Isaac Newton', 'Albert Einstein', 'Alexander Fleming', 'D'),
('How many planets are there in our solar system?', '7', '8', '9', '10', 'B'),
('What is the name of the longest river in South America?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'A'),
('Which country is known as the Land of the Thunder Dragon?', 'Bhutan', 'Nepal', 'Tibet', 'Mongolia', 'A'),
('What is the capital of Australia?', 'Sydney', 'Melbourne', 'Brisbane', 'Canberra', 'D'),
('Who painted the Mona Lisa?', 'Vincent Van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet', 'C'),
('What is the main language spoken in Brazil?', 'Spanish', 'Portuguese', 'French', 'English', 'B'),
('What is 25 * 4?', '80', '90', '100', '110', 'C'),
('What is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Platinum', 'C'),
('What is the chemical formula for table salt?', 'NaCl', 'KCl', 'NaOH', 'HCl', 'A'),
('Who developed the theory of relativity?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla', 'B'),
('How many chambers are there in the human heart?', '2', '3', '4', '5', 'C'),
('Which country is the largest by area?', 'China', 'United States', 'Russia', 'Canada', 'C'),
('Who wrote "Pride and Prejudice"?', 'Charlotte Bronte', 'Jane Austen', 'Emily Bronte', 'Mary Shelley', 'B'),
('What is the capital of China?', 'Shanghai', 'Beijing', 'Hong Kong', 'Guangzhou', 'B'),
('Which element is known as the building block of life?', 'Hydrogen', 'Oxygen', 'Carbon', 'Nitrogen', 'C'),
('What is the primary source of energy for the Earth?', 'The Moon', 'The Sun', 'The Wind', 'The Ocean', 'B'),
('Which of the following is a chemical change?', 'Melting of ice', 'Boiling of water', 'Rusting of iron', 'Breaking of glass', 'C'),
('How many continents are there?', '5', '6', '7', '8', 'C'),
('What is the speed of light?', '300,000 km/s', '150,000 km/s', '100,000 km/s', '200,000 km/s', 'A'),
('Who is known as the father of computers?', 'Charles Babbage', 'Alan Turing', 'Bill Gates', 'Steve Jobs', 'A'),
('What is the formula for calculating the circumference of a circle?', 'πr²', '2πr', 'πd', '2r', 'B'),
('Which planet is known for its rings?', 'Mars', 'Jupiter', 'Saturn', 'Neptune', 'C'),
('What is the capital of Russia?', 'Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'A'),
('What is the largest island in the world?', 'Greenland', 'New Guinea', 'Borneo', 'Madagascar', 'A'),
('What is the main gas found in the air we breathe?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 'B'),
('How many states are there in the United States?', '48', '49', '50', '51', 'C'),
('What is the currency of the United Kingdom?', 'Euro', 'Dollar', 'Pound', 'Yen', 'C'),
('Which country is known as the land of a thousand lakes?', 'Norway', 'Sweden', 'Finland', 'Denmark', 'C');

INSERT INTO quiz (question_text, option_1, option_2, option_3, option_4, correct_answer) VALUES
('What is the chemical symbol for gold?', 'Au', 'Ag', 'Pb', 'Hg', 'A'),
('Which planet has the most moons?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'C'),
('What is the capital of Spain?', 'Madrid', 'Barcelona', 'Seville', 'Valencia', 'A'),
('Who wrote "The Odyssey"?', 'Homer', 'Virgil', 'Shakespeare', 'Sophocles', 'A'),
('What is 15% of 200?', '25', '30', '35', '40', 'B'),
('Which gas is essential for human respiration?', 'Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Hydrogen', 'B'),
('What is the value of the mathematical constant "e" (Eulers number) to two decimal places?', '2.71', '3.14', '1.61', '0.57', 'A'),
('How many bones are there in the adult human body?', '206', '208', '210', '212', 'A'),
('Which is the largest planet in the solar system?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'C');

create table lockques(
	id serial,
	high int,
	low int
)

INSERT INTO lockques values(1,1,10)




SELECT * FROM quiz
WHERE question_id NOT BETWEEN 20 AND 30;